#Config.yaml
# Modify data here to affect the running of the app

#---------------------------------------
# File locations

# Where the kanban database is stored
database_location: ~/.kb/test.db

# The location of the kanban-fetch binary, for refreshing
binary_location: ~/bin/kanban-fetch

# Specify additional arguments to kanban-fetch here
# (will automatically populate "--out")
binary_options:
  - -x
  - "Recurring Tasks,Template"

#---------------------------------------
# Board settings

# How many items maximum in your active board?
active_limit: 5

#---------------------------------------
# Column filters

##
# Possible statuses:
#
# * On hold: project manually marked "on hold"
# * Done: project manually marked "done"
# * Dropped: project manually marked "dropped"
# * Project deferred: Project has a deferral date in the future
# * Task deferred: First available task has a deferral date in the future (project is active)
# * Waiting on: First available task has a context that starts with "Waiting"
# * Hanging: No available tasks
# * Active: Project active, first task available
##

# Which statuses show up in your backburner?

backburner_filter:
  - On hold
  - Project deferred

# Which statuses show up in your completed?
completed_filter:
  - Done
  - Dropped

# Everything else shows up in active